apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smart-lock-api-hpa
  namespace: smart-lock
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-lock-api
  minReplicas: 2
  maxReplicas: 10 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70